# **# INSTALANDO BIBLIOTECAS**

In [1]:
! pip install yfinance
! pip install investpy
! pip install matplotlib
! pip install pandas
! pip install requests
! pip install datetime
! pip install yahooquery
! pip install finnhub-python

Requirement already satisfied: yfinance in c:\program files\python313\lib\site-packages (0.2.49)
Requirement already satisfied: pandas>=1.3.0 in c:\program files\python313\lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\program files\python313\lib\site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in c:\program files\python313\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\program files\python313\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\program files\python313\lib\site-packages (from yfinance) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in c:\program files\python313\lib\site-packages (from yfinance) (2024.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\program files\python313\lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\program files\python313\lib\site-packages (from yfinance) (3.17.7)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\program files\python313\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in c:\program files\python313\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\program files\python313\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: six>=1.9 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\program files\python313\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas>=1.3.0->yfinance) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (2024.8.30)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: investpy in c:\program files\python313\lib\site-packages (1.0.8)
Requirement already satisfied: Unidecode>=1.1.1 in c:\program files\python313\lib\site-packages (from investpy) (1.3.8)
Requirement already satisfied: setuptools>=41.2.0 in c:\program files\python313\lib\site-packages (from investpy) (75.4.0)
Requirement already satisfied: numpy>=1.17.2 in c:\program files\python313\lib\site-packages (from investpy) (2.1.3)
Requirement already satisfied: pandas>=0.25.1 in c:\program files\python313\lib\site-packages (from investpy) (2.2.3)
Requirement already satisfied: lxml>=4.4.1 in c:\program files\python313\lib\site-packages (from investpy) (5.3.0)
Requirement already satisfied: requests>=2.22.0 in c:\program files\python313\lib\site-packages (from investpy) (2.32.3)
Requirement already satisfied: pytz>=2019.3 in c:\program files\python313\lib\site-packages (from investpy) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas>=0.25.1->investpy) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas>=0.25.1->investpy) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (2024.8.30)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=0.25.1->investpy) (1.16.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\program files\python313\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\program files\python313\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\program files\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\program files\python313\lib\site-packages (from matplotlib) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\program files\python313\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy>=1.23 in c:\program files\python313\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\program files\python313\lib\site-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\program files\python313\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\program files\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\program files\python313\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: requests in c:\program files\python313\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests) (2024.8.30)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: datetime in c:\program files\python313\lib\site-packages (5.5)
Requirement already satisfied: zope.interface in c:\program files\python313\lib\site-packages (from datetime) (7.1.1)
Requirement already satisfied: pytz in c:\program files\python313\lib\site-packages (from datetime) (2024.2)
Requirement already satisfied: setuptools in c:\program files\python313\lib\site-packages (from zope.interface->datetime) (75.4.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: yahooquery in c:\program files\python313\lib\site-packages (2.4.1)
Requirement already satisfied: beautifulsoup4>=4.12.2 in c:\program files\python313\lib\site-packages (from yahooquery) (4.12.3)
Requirement already satisfied: curl-cffi>=0.10.0 in c:\program files\python313\lib\site-packages (from yahooquery) (0.11.4)
Requirement already satisfied: lxml>=4.9.3 in c:\program files\python313\lib\site-packages (from yahooquery) (5.3.0)
Requirement already satisfied: pandas>=2.2.0 in c:\program files\python313\lib\site-packages (from yahooquery) (2.2.3)
Requirement already satisfied: requests-futures>=1.0.1 in c:\program files\python313\lib\site-packages (from yahooquery) (1.0.2)
Requirement already satisfied: tqdm>=4.65.0 in c:\program files\python313\lib\site-packages (from yahooquery) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in c:\program files\python313\lib\site-packages (from beautifulsoup4>=4.12.2->yahooquery) (2.6)
Requirement already satisfied: cffi>=1.12.0 in c:\program files\python313\lib\site-packages (from curl-cffi>=0.10.0->yahooquery) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\program files\python313\lib\site-packages (from curl-cffi>=0.10.0->yahooquery) (2024.8.30)
Requirement already satisfied: numpy>=1.26.0 in c:\program files\python313\lib\site-packages (from pandas>=2.2.0->yahooquery) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas>=2.2.0->yahooquery) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python313\lib\site-packages (from pandas>=2.2.0->yahooquery) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas>=2.2.0->yahooquery) (2024.2)
Requirement already satisfied: requests>=1.2.0 in c:\program files\python313\lib\site-packages (from requests-futures>=1.0.1->yahooquery) (2.32.3)
Requirement already satisfied: colorama in c:\users\b48k\appdata\roaming\python\python313\site-packages (from tqdm>=4.65.0->yahooquery) (0.4.6)
Requirement already satisfied: pycparser in c:\program files\python313\lib\site-packages (from cffi>=1.12.0->curl-cffi>=0.10.0->yahooquery) (2.22)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->yahooquery) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.1->yahooquery) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.1->yahooquery) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.1->yahooquery) (2.2.3)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: finnhub-python in c:\program files\python313\lib\site-packages (2.4.21)
Requirement already satisfied: requests>=2.22.0 in c:\program files\python313\lib\site-packages (from finnhub-python) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->finnhub-python) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->finnhub-python) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->finnhub-python) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->finnhub-python) (2024.8.30)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# **# IMPORTANDO MÓDULOS**

In [2]:
import yfinance as yf
import investpy as ip
import matplotlib as mp
import pandas as pd
import requests as rq
import datetime as dt
import yahooquery as yq
import finnhub as fp

import numpy as np
import string as st
import warnings as wa
import matplotlib.pyplot as plt
import openpyxl as op
import xlrd as xlrd
import seaborn as sns
from bs4 import BeautifulSoup

#warnings.filterwarnings('ignore')

# **# IMPORTANDO ARQUIVO: DADOS PAPEIS GITHUB**

In [3]:
Arq_Dados_Papeis = op.load_workbook('00_DADOS_PAPEIS_GITHUB.xlsx')                                 # Carregando arquivo Excel ReesultadoFM.xlxl
Plan_Dados_Papeis = Arq_Dados_Papeis['Sheet1']                                                       # Carregando planilha Excel expec[ifica em ReesultadoFM.xlxl
Arq_Dados_Papeis

In [4]:
ArqLer_Dados_Papeis = pd.read_excel('00_DADOS_PAPEIS_GITHUB.xlsx')                                 # Lendo arquivo Excel ReesultadoFM.xlxl
ArqLer_Dados_Papeis

,Unnamed: 0,CNPJ_Companhia,Nome_Empresarial,Data_Constituicao,Codigo_CVM,Data_Registro_CVM,Situacao_Registro_CVM,Pais_Origem,Pais_Custodia_Valores_Mobiliarios,Setor_Atividade,...,P/Ativo_Circ_Líq,Classificação Capitalização,Crescimento esperado LPA,Crescimento esperado EBIT,Crescimento EBIT,Crescimento Margem EBIT,Crescimento LPA,Crescimento Receita,Proventos no Período,Dividend Yield
0,0,09.149.503/0001-06,OMEGA ENERGIA RENOVÁVEL S/A,2007-09-26,22110,2010-07-29,Ativo,Brasil,A companhia não possui valores mobiliários sob...,Emp. Adm. Part. - Energia Elétrica,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,09.149.503/0001-06,OMEGA ENERGIA RENOVÁVEL S/A,2007-09-26,22110,2010-07-29,Ativo,Brasil,A companhia não possui valores mobiliários sob...,Emp. Adm. Part. - Energia Elétrica,...,0.000000,NaN,-0.011134,NaN,1.509728,2.662904,-0.254327,-0.314826,NaN,NaN
2,2,09.149.503/0001-06,OMEGA ENERGIA RENOVÁVEL S/A,2007-09-26,22110,2010-07-29,Ativo,Brasil,A companhia não possui valores mobiliários sob...,Emp. Adm. Part. - Energia Elétrica,...,0.000000,NaN,-0.008726,NaN,-1.253488,-1.049003,0.278886,4.172875,NaN,NaN
3,3,09.149.503/0001-06,OMEGA ENERGIA RENOVÁVEL S/A,2007-09-26,22110,2010-07-29,Ativo,Brasil,A companhia não possui valores mobiliários sob...,Emp. Adm. Part. - Energia Elétrica,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,09.149.503/0001-06,OMEGA ENERGIA RENOVÁVEL S/A,2007-09-26,22110,2010-07-29,Ativo,Brasil,A companhia não possui valores mobiliários sob...,Emp. Adm. Part. - Energia Elétrica,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28922,28922,97.837.181/0001-47,DEXCO S.A.,1962-01-25,21091,2007-09-10,Ativo,Brasil,Brasil,"Construção Civil, Mat. Constr. e Decoração",...,-1.112928,Mid Cap,0.005133,NaN,-0.843060,-0.818569,-0.926454,-0.134985,NaN,NaN
28923,28923,97.837.181/0001-47,DEXCO S.A.,1962-01-25,21091,2007-09-10,Ativo,Brasil,Brasil,"Construção Civil, Mat. Constr. e Decoração",...,-1.642665,Large Cap,0.025992,NaN,1.441054,0.796245,3.476782,0.358976,NaN,NaN
28924,28924,97.837.181/0001-47,DEXCO S.A.,1962-01-25,21091,2007-09-10,Ativo,Brasil,Brasil,"Construção Civil, Mat. Constr. e Decoração",...,-1.999919,Large Cap,0.052309,NaN,0.813193,0.480793,0.873174,0.224474,NaN,NaN
28925,28925,97.837.181/0001-47,DEXCO S.A.,1962-01-25,21091,2007-09-10,Ativo,Brasil,Brasil,"Construção Civil, Mat. Constr. e Decoração",...,-2.500198,Large Cap,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28926,28926,97.837.181/0001-47,DEXCO S.A.,1962-01-25,21091,2007-09-10,Ativo,Brasil,Brasil,"Construção Civil, Mat. Constr. e Decoração",...,0.000000,NaN,0.178697,0.090973,1.408015,0.830370,NaN,0.315590,1.280687,inf

In [5]:
ArqLer_Dados_Papeis.columns

Index(['Unnamed: 0', 'CNPJ_Companhia', 'Nome_Empresarial', 'Data_Constituicao',
       'Codigo_CVM', 'Data_Registro_CVM', 'Situacao_Registro_CVM',
       'Pais_Origem', 'Pais_Custodia_Valores_Mobiliarios', 'Setor_Atividade',
       ...
       'P/Ativo_Circ_Líq', 'Classificação Capitalização',
       'Crescimento esperado LPA', 'Crescimento esperado EBIT',
       'Crescimento EBIT', 'Crescimento Margem EBIT', 'Crescimento LPA',
       'Crescimento Receita', 'Proventos no Período', 'Dividend Yield'],
      dtype='object', length=178)

In [6]:
Dados_Papeis = ArqLer_Dados_Papeis[['CODIGO', 'Data_Registro_CVM', 'Situacao_Registro_CVM', 'Patrimônio Líquido Consolidado', 'trimestre', 'ano', 'ROIC', 'EV/EBIT', 'SETOR']]     # CRIAÇÃO DE UMA NOVA VARIÁVEL APENAS COM AS INFORMAÇÕES NECESSSÁRIAS PARA A FÓRMULA
Dados_Papeis

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
0,OMGE3,2010-07-29,Ativo,2.160950e+08,1 trim,2011,NaN,-55.556420,Utilidade pública
1,OMGE3,2010-07-29,Ativo,3.526100e+08,1 trim,2012,-0.008935,-0.006977,Utilidade pública
2,OMGE3,2010-07-29,Ativo,5.143430e+08,1 trim,2013,-0.002328,71.614679,Utilidade pública
3,OMGE3,2010-07-29,Ativo,2.178240e+08,annual,2010,NaN,-1.025882,Utilidade pública
4,OMGE3,2010-07-29,Ativo,2.178240e+08,4 trim,2010,NaN,-2.549597,Utilidade pública
...,...,...,...,...,...,...,...,...,...
28922,DTEX3,2007-09-10,Ativo,4.766336e+09,3 trim,2019,0.011505,111.285963,Materiais básicos
28923,DTEX3,2007-09-10,Ativo,4.879993e+09,3 trim,2020,0.022646,60.707130,Materiais básicos
28924,DTEX3,2007-09-10,Ativo,6.015095e+09,3 trim,2021,0.038932,42.478876,Materiais básicos
28925,DTEX3,2007-09-10,Ativo,5.025102e+09,annual,2021,NaN,23.917844,Materiais básicos
28926,DTEX3,2007-09-10,Ativo,5.504997e+09,annual,2022,0.256590,1.565200,Materiais básicos

In [7]:
Dados_Papeis = Dados_Papeis.fillna(0)     # SUBSTITUINDO VALORES NULOS POR 0 (ZERO) PARA EVITAR PROBLEMAS NA HORA DE APLICAR A FÓRMULA
Dados_Papeis

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
0,OMGE3,2010-07-29,Ativo,2.160950e+08,1 trim,2011,0.000000,-55.556420,Utilidade pública
1,OMGE3,2010-07-29,Ativo,3.526100e+08,1 trim,2012,-0.008935,-0.006977,Utilidade pública
2,OMGE3,2010-07-29,Ativo,5.143430e+08,1 trim,2013,-0.002328,71.614679,Utilidade pública
3,OMGE3,2010-07-29,Ativo,2.178240e+08,annual,2010,0.000000,-1.025882,Utilidade pública
4,OMGE3,2010-07-29,Ativo,2.178240e+08,4 trim,2010,0.000000,-2.549597,Utilidade pública
...,...,...,...,...,...,...,...,...,...
28922,DTEX3,2007-09-10,Ativo,4.766336e+09,3 trim,2019,0.011505,111.285963,Materiais básicos
28923,DTEX3,2007-09-10,Ativo,4.879993e+09,3 trim,2020,0.022646,60.707130,Materiais básicos
28924,DTEX3,2007-09-10,Ativo,6.015095e+09,3 trim,2021,0.038932,42.478876,Materiais básicos
28925,DTEX3,2007-09-10,Ativo,5.025102e+09,annual,2021,0.000000,23.917844,Materiais básicos
28926,DTEX3,2007-09-10,Ativo,5.504997e+09,annual,2022,0.256590,1.565200,Materiais básicos

# **# FILTRANDO POR ANO DE REGISTRO NA CVM**

In [8]:

Dados_Papeis_Filtro_Ano = Dados_Papeis[ Dados_Papeis['Data_Registro_CVM'].str[:4].astype(int) < 2011 ]
Dados_Papeis_Filtro_Ano

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
0,OMGE3,2010-07-29,Ativo,2.160950e+08,1 trim,2011,0.000000,-55.556420,Utilidade pública
1,OMGE3,2010-07-29,Ativo,3.526100e+08,1 trim,2012,-0.008935,-0.006977,Utilidade pública
2,OMGE3,2010-07-29,Ativo,5.143430e+08,1 trim,2013,-0.002328,71.614679,Utilidade pública
3,OMGE3,2010-07-29,Ativo,2.178240e+08,annual,2010,0.000000,-1.025882,Utilidade pública
4,OMGE3,2010-07-29,Ativo,2.178240e+08,4 trim,2010,0.000000,-2.549597,Utilidade pública
...,...,...,...,...,...,...,...,...,...
28922,DTEX3,2007-09-10,Ativo,4.766336e+09,3 trim,2019,0.011505,111.285963,Materiais básicos
28923,DTEX3,2007-09-10,Ativo,4.879993e+09,3 trim,2020,0.022646,60.707130,Materiais básicos
28924,DTEX3,2007-09-10,Ativo,6.015095e+09,3 trim,2021,0.038932,42.478876,Materiais básicos
28925,DTEX3,2007-09-10,Ativo,5.025102e+09,annual,2021,0.000000,23.917844,Materiais básicos
28926,DTEX3,2007-09-10,Ativo,5.504997e+09,annual,2022,0.256590,1.565200,Materiais básicos

# **# FILTRANDO POR SITUAÇÃO**

In [9]:

Dados_Papeis_Filtro_Situacao = Dados_Papeis_Filtro_Ano[ Dados_Papeis_Filtro_Ano['Situacao_Registro_CVM'] == "Ativo" ]
Dados_Papeis_Filtro_Situacao

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
0,OMGE3,2010-07-29,Ativo,2.160950e+08,1 trim,2011,0.000000,-55.556420,Utilidade pública
1,OMGE3,2010-07-29,Ativo,3.526100e+08,1 trim,2012,-0.008935,-0.006977,Utilidade pública
2,OMGE3,2010-07-29,Ativo,5.143430e+08,1 trim,2013,-0.002328,71.614679,Utilidade pública
3,OMGE3,2010-07-29,Ativo,2.178240e+08,annual,2010,0.000000,-1.025882,Utilidade pública
4,OMGE3,2010-07-29,Ativo,2.178240e+08,4 trim,2010,0.000000,-2.549597,Utilidade pública
...,...,...,...,...,...,...,...,...,...
28922,DTEX3,2007-09-10,Ativo,4.766336e+09,3 trim,2019,0.011505,111.285963,Materiais básicos
28923,DTEX3,2007-09-10,Ativo,4.879993e+09,3 trim,2020,0.022646,60.707130,Materiais básicos
28924,DTEX3,2007-09-10,Ativo,6.015095e+09,3 trim,2021,0.038932,42.478876,Materiais básicos
28925,DTEX3,2007-09-10,Ativo,5.025102e+09,annual,2021,0.000000,23.917844,Materiais básicos
28926,DTEX3,2007-09-10,Ativo,5.504997e+09,annual,2022,0.256590,1.565200,Materiais básicos

# **# FILTRANDO POR PATRIMÔNIO LÍQUIDO POSITIVO**

In [10]:
Dados_Papeis_Filtro_Patrimonio = Dados_Papeis_Filtro_Situacao[Dados_Papeis_Filtro_Situacao['Patrimônio Líquido Consolidado'] > 0]
Dados_Papeis_Filtro_Patrimonio

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
0,OMGE3,2010-07-29,Ativo,2.160950e+08,1 trim,2011,0.000000,-55.556420,Utilidade pública
1,OMGE3,2010-07-29,Ativo,3.526100e+08,1 trim,2012,-0.008935,-0.006977,Utilidade pública
2,OMGE3,2010-07-29,Ativo,5.143430e+08,1 trim,2013,-0.002328,71.614679,Utilidade pública
3,OMGE3,2010-07-29,Ativo,2.178240e+08,annual,2010,0.000000,-1.025882,Utilidade pública
4,OMGE3,2010-07-29,Ativo,2.178240e+08,4 trim,2010,0.000000,-2.549597,Utilidade pública
...,...,...,...,...,...,...,...,...,...
28922,DTEX3,2007-09-10,Ativo,4.766336e+09,3 trim,2019,0.011505,111.285963,Materiais básicos
28923,DTEX3,2007-09-10,Ativo,4.879993e+09,3 trim,2020,0.022646,60.707130,Materiais básicos
28924,DTEX3,2007-09-10,Ativo,6.015095e+09,3 trim,2021,0.038932,42.478876,Materiais básicos
28925,DTEX3,2007-09-10,Ativo,5.025102e+09,annual,2021,0.000000,23.917844,Materiais básicos
28926,DTEX3,2007-09-10,Ativo,5.504997e+09,annual,2022,0.256590,1.565200,Materiais básicos

# **# FILTRANDO POR ANO DOS DADOS**

In [11]:

Dados_Papeis_AnoDados = Dados_Papeis_Filtro_Patrimonio[Dados_Papeis_Filtro_Patrimonio['ano'].astype(int) == 2010]
Dados_Papeis_AnoDados

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
3,OMGE3,2010-07-29,Ativo,2.178240e+08,annual,2010,0.000000,-1.025882,Utilidade pública
4,OMGE3,2010-07-29,Ativo,2.178240e+08,4 trim,2010,0.000000,-2.549597,Utilidade pública
112,LAME3,1977-07-20,Ativo,5.506780e+08,annual,2010,0.489684,6.643312,Consumo cíclico
113,LAME3,1977-07-20,Ativo,5.506780e+08,4 trim,2010,0.000000,16.306781,Consumo cíclico
172,LAME4,1977-07-20,Ativo,5.506780e+08,annual,2010,0.489684,6.643312,Consumo cíclico
...,...,...,...,...,...,...,...,...,...
28606,YDUQ3,2007-07-26,Ativo,5.858980e+08,4 trim,2010,0.000000,36.882987,Consumo cíclico
28669,TRIS3,2007-10-10,Ativo,5.084130e+08,annual,2010,0.076821,10.678534,Consumo cíclico
28670,TRIS3,2007-10-10,Ativo,5.084130e+08,4 trim,2010,0.000000,-202.035513,Consumo cíclico
28877,DTEX3,2007-09-10,Ativo,3.452528e+09,annual,2010,0.132657,7.190138,Materiais básicos
28878,DTEX3,2007-09-10,Ativo,3.452528e+09,4 trim,2010,0.000000,26.167449,Materiais básicos

In [12]:
Dados_Papeis_AnoDado_Trim = Dados_Papeis_AnoDados[Dados_Papeis_AnoDados['trimestre'] == 'annual']
Dados_Papeis_AnoDado_Trim

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
3,OMGE3,2010-07-29,Ativo,2.178240e+08,annual,2010,0.000000,-1.025882,Utilidade pública
112,LAME3,1977-07-20,Ativo,5.506780e+08,annual,2010,0.489684,6.643312,Consumo cíclico
172,LAME4,1977-07-20,Ativo,5.506780e+08,annual,2010,0.489684,6.643312,Consumo cíclico
257,RPAD3,1977-07-20,Ativo,6.049630e+08,annual,2010,0.033301,27.509527,Financeiro
312,RPAD5,1977-07-20,Ativo,6.049630e+08,annual,2010,0.033301,27.509527,Financeiro
...,...,...,...,...,...,...,...,...,...
28396,GSHP3,2007-07-26,Ativo,3.711140e+08,annual,2010,0.140645,75.681502,Financeiro
28541,CCPR3,2007-08-01,Ativo,5.046880e+08,annual,2010,0.212735,6.076027,Financeiro
28605,YDUQ3,2007-07-26,Ativo,5.858980e+08,annual,2010,0.204162,6.317414,Consumo cíclico
28669,TRIS3,2007-10-10,Ativo,5.084130e+08,annual,2010,0.076821,10.678534,Consumo cíclico
28877,DTEX3,2007-09-10,Ativo,3.452528e+09,annual,2010,0.132657,7.190138,Materiais básicos

# **# CRIANDO ARQUIVO EXCEL PARA CARTEIRA FM**

In [13]:
Dados_Filtrados_Github = Dados_Papeis_AnoDado_Trim
Dados_Filtrados_Github

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
3,OMGE3,2010-07-29,Ativo,2.178240e+08,annual,2010,0.000000,-1.025882,Utilidade pública
112,LAME3,1977-07-20,Ativo,5.506780e+08,annual,2010,0.489684,6.643312,Consumo cíclico
172,LAME4,1977-07-20,Ativo,5.506780e+08,annual,2010,0.489684,6.643312,Consumo cíclico
257,RPAD3,1977-07-20,Ativo,6.049630e+08,annual,2010,0.033301,27.509527,Financeiro
312,RPAD5,1977-07-20,Ativo,6.049630e+08,annual,2010,0.033301,27.509527,Financeiro
...,...,...,...,...,...,...,...,...,...
28396,GSHP3,2007-07-26,Ativo,3.711140e+08,annual,2010,0.140645,75.681502,Financeiro
28541,CCPR3,2007-08-01,Ativo,5.046880e+08,annual,2010,0.212735,6.076027,Financeiro
28605,YDUQ3,2007-07-26,Ativo,5.858980e+08,annual,2010,0.204162,6.317414,Consumo cíclico
28669,TRIS3,2007-10-10,Ativo,5.084130e+08,annual,2010,0.076821,10.678534,Consumo cíclico
28877,DTEX3,2007-09-10,Ativo,3.452528e+09,annual,2010,0.132657,7.190138,Materiais básicos

In [14]:
Dados_Filtrados_Github.to_excel('0_1_1_Dados_Filtrados_Github.xlsx', index=False, engine='openpyxl')   # Criando arquivo Excel ReesultadoFM.xlxl
print("Arquivo Excel 0_1_1_Dados_Filtrados_Github criado com sucesso!")                                 # Confirmando a criação do arquivo excel ReesultadoFM.xlxl

Arquivo Excel 0_1_1_Dados_Filtrados_Github criado com sucesso!

In [15]:
Arq_0_1_1_Dados_Filtrados_Github= op.load_workbook('0_1_1_Dados_Filtrados_Github.xlsx')                                 # Carregando arquivo Excel ReesultadoFM.xlxl
Plan_0_1_1_Dados_Filtrados_Github = Arq_0_1_1_Dados_Filtrados_Github['Sheet1']                                                       # Carregando planilha Excel expec[ifica em ReesultadoFM.xlxl
Arq_0_1_1_Dados_Filtrados_Github

In [16]:
ArqLer_Arq_0_1_1_Dados_Filtrados_Github = pd.read_excel('0_1_1_Dados_Filtrados_Github.xlsx')                                 # Lendo arquivo Excel ReesultadoFM.xlxl
ArqLer_Arq_0_1_1_Dados_Filtrados_Github

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
0,OMGE3,2010-07-29,Ativo,217824000,annual,2010,0.000000,-1.025882,Utilidade pública
1,LAME3,1977-07-20,Ativo,550678000,annual,2010,0.489684,6.643312,Consumo cíclico
2,LAME4,1977-07-20,Ativo,550678000,annual,2010,0.489684,6.643312,Consumo cíclico
3,RPAD3,1977-07-20,Ativo,604963000,annual,2010,0.033301,27.509527,Financeiro
4,RPAD5,1977-07-20,Ativo,604963000,annual,2010,0.033301,27.509527,Financeiro
...,...,...,...,...,...,...,...,...,...
359,GSHP3,2007-07-26,Ativo,371114000,annual,2010,0.140645,75.681502,Financeiro
360,CCPR3,2007-08-01,Ativo,504688000,annual,2010,0.212735,6.076027,Financeiro
361,YDUQ3,2007-07-26,Ativo,585898000,annual,2010,0.204162,6.317414,Consumo cíclico
362,TRIS3,2007-10-10,Ativo,508413000,annual,2010,0.076821,10.678534,Consumo cíclico
363,DTEX3,2007-09-10,Ativo,3452528000,annual,2010,0.132657,7.190138,Materiais básicos