# **# INSTALANDO BIBLIOTECAS**

In [1]:
! pip install yfinance
! pip install investpy
! pip install matplotlib
! pip install pandas
! pip install requests
! pip install datetime
! pip install yahooquery
! pip install finnhub-python

Requirement already satisfied: yfinance in c:\program files\python313\lib\site-packages (0.2.49)
Requirement already satisfied: pandas>=1.3.0 in c:\program files\python313\lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\program files\python313\lib\site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in c:\program files\python313\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\program files\python313\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\program files\python313\lib\site-packages (from yfinance) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in c:\program files\python313\lib\site-packages (from yfinance) (2024.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\program files\python313\lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\program files\python313\lib\site-packages (from yfinance) (3.17.7)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\program files\python313\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in c:\program files\python313\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\program files\python313\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: six>=1.9 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\program files\python313\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas>=1.3.0->yfinance) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (2024.8.30)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: investpy in c:\program files\python313\lib\site-packages (1.0.8)
Requirement already satisfied: Unidecode>=1.1.1 in c:\program files\python313\lib\site-packages (from investpy) (1.3.8)
Requirement already satisfied: setuptools>=41.2.0 in c:\program files\python313\lib\site-packages (from investpy) (75.4.0)
Requirement already satisfied: numpy>=1.17.2 in c:\program files\python313\lib\site-packages (from investpy) (2.1.3)
Requirement already satisfied: pandas>=0.25.1 in c:\program files\python313\lib\site-packages (from investpy) (2.2.3)
Requirement already satisfied: lxml>=4.4.1 in c:\program files\python313\lib\site-packages (from investpy) (5.3.0)
Requirement already satisfied: requests>=2.22.0 in c:\program files\python313\lib\site-packages (from investpy) (2.32.3)
Requirement already satisfied: pytz>=2019.3 in c:\program files\python313\lib\site-packages (from investpy) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas>=0.25.1->investpy) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas>=0.25.1->investpy) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (2024.8.30)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=0.25.1->investpy) (1.16.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\program files\python313\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\program files\python313\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\program files\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\program files\python313\lib\site-packages (from matplotlib) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\program files\python313\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy>=1.23 in c:\program files\python313\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\program files\python313\lib\site-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\program files\python313\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\program files\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\program files\python313\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: requests in c:\program files\python313\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests) (2024.8.30)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: datetime in c:\program files\python313\lib\site-packages (5.5)
Requirement already satisfied: zope.interface in c:\program files\python313\lib\site-packages (from datetime) (7.1.1)
Requirement already satisfied: pytz in c:\program files\python313\lib\site-packages (from datetime) (2024.2)
Requirement already satisfied: setuptools in c:\program files\python313\lib\site-packages (from zope.interface->datetime) (75.4.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: yahooquery in c:\program files\python313\lib\site-packages (2.4.1)
Requirement already satisfied: beautifulsoup4>=4.12.2 in c:\program files\python313\lib\site-packages (from yahooquery) (4.12.3)
Requirement already satisfied: curl-cffi>=0.10.0 in c:\program files\python313\lib\site-packages (from yahooquery) (0.11.4)
Requirement already satisfied: lxml>=4.9.3 in c:\program files\python313\lib\site-packages (from yahooquery) (5.3.0)
Requirement already satisfied: pandas>=2.2.0 in c:\program files\python313\lib\site-packages (from yahooquery) (2.2.3)
Requirement already satisfied: requests-futures>=1.0.1 in c:\program files\python313\lib\site-packages (from yahooquery) (1.0.2)
Requirement already satisfied: tqdm>=4.65.0 in c:\program files\python313\lib\site-packages (from yahooquery) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in c:\program files\python313\lib\site-packages (from beautifulsoup4>=4.12.2->yahooquery) (2.6)
Requirement already satisfied: cffi>=1.12.0 in c:\program files\python313\lib\site-packages (from curl-cffi>=0.10.0->yahooquery) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\program files\python313\lib\site-packages (from curl-cffi>=0.10.0->yahooquery) (2024.8.30)
Requirement already satisfied: numpy>=1.26.0 in c:\program files\python313\lib\site-packages (from pandas>=2.2.0->yahooquery) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas>=2.2.0->yahooquery) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python313\lib\site-packages (from pandas>=2.2.0->yahooquery) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas>=2.2.0->yahooquery) (2024.2)
Requirement already satisfied: requests>=1.2.0 in c:\program files\python313\lib\site-packages (from requests-futures>=1.0.1->yahooquery) (2.32.3)
Requirement already satisfied: colorama in c:\users\b48k\appdata\roaming\python\python313\site-packages (from tqdm>=4.65.0->yahooquery) (0.4.6)
Requirement already satisfied: pycparser in c:\program files\python313\lib\site-packages (from cffi>=1.12.0->curl-cffi>=0.10.0->yahooquery) (2.22)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->yahooquery) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.1->yahooquery) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.1->yahooquery) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=1.2.0->requests-futures>=1.0.1->yahooquery) (2.2.3)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: finnhub-python in c:\program files\python313\lib\site-packages (2.4.21)
Requirement already satisfied: requests>=2.22.0 in c:\program files\python313\lib\site-packages (from finnhub-python) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->finnhub-python) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->finnhub-python) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->finnhub-python) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->finnhub-python) (2024.8.30)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# **# IMPORTANDO MÓDULOS**

In [2]:
import yfinance as yf
import investpy as ip
import matplotlib as mp
import pandas as pd
import requests as rq
import datetime as dt
import yahooquery as yq
import finnhub as fp

import numpy as np
import string as st
import warnings as wa
import matplotlib.pyplot as plt
import openpyxl as op
import xlrd as xlrd
import seaborn as sns
from bs4 import BeautifulSoup

#warnings.filterwarnings('ignore')

# **# IMPORTANDO ARQUIVO: 0_3_3_DADOS_GITHUB_FECHADOS.xlsx**

In [3]:
Arq_DADOS_GITHUB_FECHADOS = op.load_workbook('0_3_3_DADOS_GITHUB_FECHADOS.xlsx')                                 # Carregando arquivo Excel ReesultadoFM.xlxl
Plan_DADOS_GITHUB_FECHADOS = Arq_DADOS_GITHUB_FECHADOS['Sheet1']                                                       # Carregando planilha Excel expec[ifica em ReesultadoFM.xlxl
Arq_DADOS_GITHUB_FECHADOS

In [4]:
ArqLer_DADOS_GITHUB_FECHADOS = pd.read_excel('0_3_3_DADOS_GITHUB_FECHADOS.xlsx')                                 # Lendo arquivo Excel ReesultadoFM.xlxl
ArqLer_DADOS_GITHUB_FECHADOS

,CODIGO,Data_Registro_CVM,Situacao_Registro_CVM,Patrimônio Líquido Consolidado,trimestre,ano,ROIC,EV/EBIT,SETOR
0,RPAD3,1977-07-20,Ativo,604963000,annual,2010,0.033301,27.509527,Financeiro
1,RPAD5,1977-07-20,Ativo,604963000,annual,2010,0.033301,27.509527,Financeiro
2,RPAD6,1977-07-20,Ativo,604963000,annual,2010,0.033301,27.509527,Financeiro
3,CRIV3,1977-07-20,Ativo,579474000,annual,2010,0.000000,0.000000,Financeiro
4,CRIV4,1977-07-20,Ativo,579474000,annual,2010,0.000000,0.000000,Financeiro
...,...,...,...,...,...,...,...,...,...
283,OSXB3,2008-02-26,Ativo,2434016000,annual,2010,0.000000,-117.614414,Petróleo gás e biocombustíveis
284,B3SA3,2008-08-11,Ativo,19419048000,annual,2010,0.052876,3.289176,Financeiro
285,GSHP3,2007-07-26,Ativo,371114000,annual,2010,0.140645,75.681502,Financeiro
286,YDUQ3,2007-07-26,Ativo,585898000,annual,2010,0.204162,6.317414,Consumo cíclico
287,TRIS3,2007-10-10,Ativo,508413000,annual,2010,0.076821,10.678534,Consumo cíclico

In [5]:
DADOS_PAPEIS = ArqLer_DADOS_GITHUB_FECHADOS[['CODIGO', 'ROIC', 'EV/EBIT', 'SETOR']]
DADOS_PAPEIS

    CODIGO      ROIC     EV/EBIT                           SETOR
0    RPAD3  0.033301   27.509527                      Financeiro
1    RPAD5  0.033301   27.509527                      Financeiro
2    RPAD6  0.033301   27.509527                      Financeiro
3    CRIV3  0.000000    0.000000                      Financeiro
4    CRIV4  0.000000    0.000000                      Financeiro
..     ...       ...         ...                             ...
283  OSXB3  0.000000 -117.614414  Petróleo gás e biocombustíveis
284  B3SA3  0.052876    3.289176                      Financeiro
285  GSHP3  0.140645   75.681502                      Financeiro
286  YDUQ3  0.204162    6.317414                 Consumo cíclico
287  TRIS3  0.076821   10.678534                 Consumo cíclico

[288 rows x 4 columns]

# **# ORDENANDO EV/EBIT**

In [6]:
EVOrdenado = DADOS_PAPEIS.sort_values(by = 'EV/EBIT')     # CRIAÇÃO DA VARIÁVEL PARA ORDENAR EV/EBIT DO MAIOR PARA O MENOR
EVOrdenado = EVOrdenado.reset_index(drop = True)
EVOrdenado['EVOrdenado'] = EVOrdenado.index
EVOrdenado

,CODIGO,ROIC,EV/EBIT,SETOR,EVOrdenado
0,CRPG5,-0.063446,-62929.736075,Materiais básicos,0
1,CRPG6,-0.063446,-62929.736075,Materiais básicos,1
2,CRPG3,-0.063446,-62929.736075,Materiais básicos,2
3,CASN4,0.012843,-267.643293,Utilidade pública,3
4,CASN3,0.012843,-267.643293,Utilidade pública,4
...,...,...,...,...,...
283,PDGR3,0.215346,6337.513517,Consumo cíclico,283
284,VIVR3,0.053256,10360.206216,Consumo cíclico,284
285,CBEE3,0.129354,11433.035909,Utilidade pública,285
286,LUPA3,0.022503,24686.443512,Petróleo gás e biocombustíveis,286
287,MTIG3,0.006042,208206.519656,Materiais básicos,287

# **# ORDENANDO ROIC**

In [7]:
RoicOrdenado = EVOrdenado.sort_values(by = 'ROIC', ascending=False)      # CRIAÇÃO DA VARIÁVEL PARA ORDENAR ROIC DO MENOR PARA O MAIOR
RoicOrdenado = RoicOrdenado.reset_index(drop = True)
RoicOrdenado['RoicOrdenado'] = RoicOrdenado.index
RoicOrdenado

,CODIGO,ROIC,EV/EBIT,SETOR,EVOrdenado,RoicOrdenado
0,BMKS3,11.094381,-1.151663,Consumo cíclico,27,0
1,BRPR3,0.513159,2.351095,Financeiro,103,1
2,PTBL3,0.491376,5.007678,Bens industriais,179,2
3,WHRL4,0.481842,2.323785,Consumo cíclico,102,3
4,WHRL3,0.481842,2.323785,Consumo cíclico,101,4
...,...,...,...,...,...,...
283,BRGE5,-2.765250,5.317941,Financeiro,185,283
284,BRGE6,-2.765250,5.317941,Financeiro,189,284
285,BRGE8,-2.765250,5.317941,Financeiro,187,285
286,BRGE7,-2.765250,5.317941,Financeiro,190,286
287,PRIO3,-2.987231,11.887785,Petróleo gás e biocombustíveis,238,287

# **# RANKING DOS DADOS**

In [8]:
Dados_Ordenados = RoicOrdenado

Dados_Ordenados['ranking'] = Dados_Ordenados['EVOrdenado'] + Dados_Ordenados['RoicOrdenado']     # ATRIBUINDO RANKING A VARIÁVEL DADOS
Dados_Ordenados.sort_values(by = 'ranking')

,CODIGO,ROIC,EV/EBIT,SETOR,EVOrdenado,RoicOrdenado,ranking
0,BMKS3,11.094381,-1.151663,Consumo cíclico,27,0,27
40,GRND3,0.237267,-1.704416,Consumo cíclico,23,40,63
25,BRKM3,0.267693,0.000000,Materiais básicos,38,25,63
26,BRKM5,0.267693,0.000000,Materiais básicos,37,26,63
54,WLMM3,0.204791,-2.438013,Bens industriais,18,54,72
...,...,...,...,...,...,...,...
223,PMAM3,0.005174,1016.159348,Materiais básicos,282,223,505
222,MTIG3,0.006042,208206.519656,Materiais básicos,287,222,509
241,DTCY3,0.000000,991.844069,Bens industriais,281,241,522
287,PRIO3,-2.987231,11.887785,Petróleo gás e biocombustíveis,238,287,525
263,MNDL3,-0.021636,55.473373,Consumo cíclico,264,263,527

# **# FILTRANDO SETORES DE ATUAÇÃO**

In [9]:
Dados_Ordenados['SETOR'].unique()     # APRESENTAÇÃO DE TODOS OS SETORES LISTADOS

array(['Consumo cíclico', 'Financeiro', 'Bens industriais',
       'Materiais básicos', 'Saúde', 'Utilidade pública',
       'Tecnologia da informação', 'Comunicações', 'Consumo não cíclico',
       'Petróleo gás e biocombustíveis'], dtype=object)

In [10]:


FiltroSetores = Dados_Ordenados[Dados_Ordenados['SETOR'] != 'Financeiro']     # RETIRADO OS SETORES CONFORME FÓRMULA
FiltroSetores = FiltroSetores[FiltroSetores['SETOR'] != 'Energia']
FiltroSetores = FiltroSetores[FiltroSetores['SETOR'] != 'Utilidade pública']
FiltroSetores = FiltroSetores[FiltroSetores['SETOR'] != 'NA']

FiltroSetores

,CODIGO,ROIC,EV/EBIT,SETOR,EVOrdenado,RoicOrdenado,ranking
0,BMKS3,11.094381,-1.151663,Consumo cíclico,27,0,27
2,PTBL3,0.491376,5.007678,Bens industriais,179,2,181
3,WHRL4,0.481842,2.323785,Consumo cíclico,102,3,105
4,WHRL3,0.481842,2.323785,Consumo cíclico,101,4,105
5,ECOR3,0.410552,2.143233,Bens industriais,95,5,100
...,...,...,...,...,...,...,...
275,BAUH4,-0.350157,-2.646829,Consumo não cíclico,16,275,291
276,BAUH3,-0.350157,-2.646829,Consumo não cíclico,17,276,293
277,AZEV4,-0.494643,0.080589,Bens industriais,69,277,346
278,AZEV3,-0.494643,0.080589,Bens industriais,70,278,348
287,PRIO3,-2.987231,11.887785,Petróleo gás e biocombustíveis,238,287,525

# **# DETERMINANDO PAPÉIS PARA CARTEIRA FÓRMULA MÁGICA**

In [12]:
CARTEIRA_FM = FiltroSetores.sort_values(by = 'ranking').head(30)  
CARTEIRA_FM

,CODIGO,ROIC,EV/EBIT,SETOR,EVOrdenado,RoicOrdenado,ranking
0,BMKS3,11.094381,-1.151663,Consumo cíclico,27,0,27
40,GRND3,0.237267,-1.704416,Consumo cíclico,23,40,63
26,BRKM5,0.267693,0.000000,Materiais básicos,37,26,63
25,BRKM3,0.267693,0.000000,Materiais básicos,38,25,63
54,WLMM3,0.204791,-2.438013,Bens industriais,18,54,72
55,WLMM4,0.204791,-2.438013,Bens industriais,19,55,74
11,PNVL3,0.316627,0.199936,Saúde,71,11,82
58,AHEB3,0.203036,-0.836552,Consumo cíclico,29,58,87
57,AHEB6,0.203036,-0.836552,Consumo cíclico,31,57,88
59,AHEB5,0.203036,-0.836552,Consumo cíclico,30,59,89
24,BRKM6,0.267693,0.000000,Materiais básicos,68,24,92
10,LREN3,0.321661,1.938122,Consumo cíclico,88,10,98
17,EALT3,0.283700,1.224220,Bens industriais,81,17,98
18,EALT4,0.283700,1.224220,Bens industriais,82,18,100
5,ECOR3,0.410552,2.143233,Bens industriais,95,5,100
4,WHRL3,0.481842,2.323785,Consumo cíclico,101,4,105
3,WHRL4,0.481842,2.323785,Consumo cíclico,102,3,105
82,SOND3,0.166554,-1.206974,Bens industriais,25,82,107
83,SOND5,0.166554,-1.206974,Bens industriais,24,83,107
37,VIVT3,0.245182,0.383979,Comunicações,72,37,109
84,SOND6,0.166554,-1.206974,Bens industriais,26,84,110
33,TOTS3,0.248579,2.207361,Tecnologia da informação,100,33,133
60,GUAR3,0.199569,0.665151,Consumo cíclico,76,60,136
27,RADL3,0.262175,2.727692,Saúde,111,27,138
23,CAMB3,0.271434,2.911895,Consumo cíclico,125,23,148
69,FESA4,0.174025,2.041730,Materiais básicos,91,69,160
68,FESA3,0.174025,2.041730,Materiais básicos,92,68,160
31,VALE3,0.258637,3.106042,Materiais básicos,135,31,166
35,BRAP3,0.247398,3.091611,Materiais básicos,133,35,168
34,BRAP4,0.247398,3.091611,Materiais básicos,134,34,168

# **# CRIANDO ARQUIVO EXCEL 0_4_4_CARTEIRA_FM**

In [13]:
CARTEIRA_FM.to_excel('0_4_4_CARTEIRA_FM.xlsx', index=False, engine='openpyxl')   # Criando arquivo Excel ReesultadoFM.xlxl
print("Arquivo 0_4_4_CARTEIRA_FM criado com sucesso!")                                 # Confirmando a criação do arquivo excel ReesultadoFM.xlxl

Arquivo 0_4_4_CARTEIRA_FM criado com sucesso!

In [14]:
Arq_CARTEIRA_FM = op.load_workbook('0_4_4_CARTEIRA_FM.xlsx')                                 # Carregando arquivo Excel ReesultadoFM.xlxl
Plan_DADOS_GITHUB_FECHADOS = Arq_CARTEIRA_FM['Sheet1']                                                       # Carregando planilha Excel expec[ifica em ReesultadoFM.xlxl
Arq_CARTEIRA_FM

In [15]:
ArqLer_CARTEIRA_FM = pd.read_excel('0_4_4_CARTEIRA_FM.xlsx')                                 # Lendo arquivo Excel ReesultadoFM.xlxl
ArqLer_CARTEIRA_FM

,CODIGO,ROIC,EV/EBIT,SETOR,EVOrdenado,RoicOrdenado,ranking
0,BMKS3,11.094381,-1.151663,Consumo cíclico,27,0,27
1,GRND3,0.237267,-1.704416,Consumo cíclico,23,40,63
2,BRKM5,0.267693,0.000000,Materiais básicos,37,26,63
3,BRKM3,0.267693,0.000000,Materiais básicos,38,25,63
4,WLMM3,0.204791,-2.438013,Bens industriais,18,54,72
5,WLMM4,0.204791,-2.438013,Bens industriais,19,55,74
6,PNVL3,0.316627,0.199936,Saúde,71,11,82
7,AHEB3,0.203036,-0.836552,Consumo cíclico,29,58,87
8,AHEB6,0.203036,-0.836552,Consumo cíclico,31,57,88
9,AHEB5,0.203036,-0.836552,Consumo cíclico,30,59,89
10,BRKM6,0.267693,0.000000,Materiais básicos,68,24,92
11,LREN3,0.321661,1.938122,Consumo cíclico,88,10,98
12,EALT3,0.283700,1.224220,Bens industriais,81,17,98
13,EALT4,0.283700,1.224220,Bens industriais,82,18,100
14,ECOR3,0.410552,2.143233,Bens industriais,95,5,100
15,WHRL3,0.481842,2.323785,Consumo cíclico,101,4,105
16,WHRL4,0.481842,2.323785,Consumo cíclico,102,3,105
17,SOND3,0.166554,-1.206974,Bens industriais,25,82,107
18,SOND5,0.166554,-1.206974,Bens industriais,24,83,107
19,VIVT3,0.245182,0.383979,Comunicações,72,37,109
20,SOND6,0.166554,-1.206974,Bens industriais,26,84,110
21,TOTS3,0.248579,2.207361,Tecnologia da informação,100,33,133
22,GUAR3,0.199569,0.665151,Consumo cíclico,76,60,136
23,RADL3,0.262175,2.727692,Saúde,111,27,138
24,CAMB3,0.271434,2.911895,Consumo cíclico,125,23,148
25,FESA4,0.174025,2.041730,Materiais básicos,91,69,160
26,FESA3,0.174025,2.041730,Materiais básicos,92,68,160
27,VALE3,0.258637,3.106042,Materiais básicos,135,31,166
28,BRAP3,0.247398,3.091611,Materiais básicos,133,35,168
29,BRAP4,0.247398,3.091611,Materiais básicos,134,34,168