# **# INSTALANDO BIBLIOTECAS**

In [1]:
! pip install yfinance
! pip install investpy
! pip install matplotlib
! pip install pandas
! pip install requests
! pip install openpyxl
! pip install xlrd
! pip install seaborn

Requirement already satisfied: yfinance in c:\program files\python313\lib\site-packages (0.2.49)
Requirement already satisfied: pandas>=1.3.0 in c:\program files\python313\lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\program files\python313\lib\site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in c:\program files\python313\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\program files\python313\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\program files\python313\lib\site-packages (from yfinance) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in c:\program files\python313\lib\site-packages (from yfinance) (2024.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\program files\python313\lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\program files\python313\lib\site-packages (from yfinance) (3.17.7)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\program files\python313\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in c:\program files\python313\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\program files\python313\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: six>=1.9 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\program files\python313\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas>=1.3.0->yfinance) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests>=2.31->yfinance) (2024.8.30)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: investpy in c:\program files\python313\lib\site-packages (1.0.8)
Requirement already satisfied: Unidecode>=1.1.1 in c:\program files\python313\lib\site-packages (from investpy) (1.3.8)
Requirement already satisfied: setuptools>=41.2.0 in c:\program files\python313\lib\site-packages (from investpy) (75.4.0)
Requirement already satisfied: numpy>=1.17.2 in c:\program files\python313\lib\site-packages (from investpy) (2.1.3)
Requirement already satisfied: pandas>=0.25.1 in c:\program files\python313\lib\site-packages (from investpy) (2.2.3)
Requirement already satisfied: lxml>=4.4.1 in c:\program files\python313\lib\site-packages (from investpy) (5.3.0)
Requirement already satisfied: requests>=2.22.0 in c:\program files\python313\lib\site-packages (from investpy) (2.32.3)
Requirement already satisfied: pytz>=2019.3 in c:\program files\python313\lib\site-packages (from investpy) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas>=0.25.1->investpy) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas>=0.25.1->investpy) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests>=2.22.0->investpy) (2024.8.30)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas>=0.25.1->investpy) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\program files\python313\lib\site-packages (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\program files\python313\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\program files\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\program files\python313\lib\site-packages (from matplotlib) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\program files\python313\lib\site-packages (from matplotlib) (1.4.7)
Requirement already satisfied: numpy>=1.23 in c:\program files\python313\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\program files\python313\lib\site-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\program files\python313\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\program files\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\program files\python313\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: requests in c:\program files\python313\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\program files\python313\lib\site-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\program files\python313\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\program files\python313\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python313\lib\site-packages (from requests) (2024.8.30)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\program files\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\program files\python313\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: xlrd in c:\program files\python313\lib\site-packages (2.0.1)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\program files\python313\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\program files\python313\lib\site-packages (from seaborn) (2.1.3)
Requirement already satisfied: pandas>=1.2 in c:\program files\python313\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\program files\python313\lib\site-packages (from seaborn) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\program files\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\program files\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\program files\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\program files\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.7)
Requirement already satisfied: packaging>=20.0 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\program files\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\program files\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\program files\python313\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\program files\python313\lib\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\b48k\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# **# IMPORTANDO MÓDULOS**

In [2]:
import yfinance as yf
import investpy as ip
import matplotlib as mp
import pandas as pd
import requests as rq
import openpyxl as op
import xlrd as xlrd
import seaborn as sns

import numpy as np
import string as st
import warnings as wa
import datetime as dt
import matplotlib.pyplot as plt

import pytz

#warnings.filterwarnings('ignore')

# **# DETERMINANDO PERÍODO DE CONSULTA PARA DADOS DO IBOVESPA (^bvsp)**

In [3]:
start = dt.datetime(2010,1,1)     # VARIÁVEL START - DEFINIÇÃO DO PERÍODOD DE CONSULTA
end = dt.datetime(2019, 12, 31)     # VARIÁVEL END

# **# BUSCANDO DADOS DO IBOVESPA (^bvsp)**

In [4]:
ibov = yf.download('^bvsp', start, end)['Adj Close']
ibov['Date'] = ibov.index
ibov

Failed to get ticker '^BVSP' reason: HTTPSConnectionPool(host='fc.yahoo.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1020)')))
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['^BVSP']: YFTzMissingError('$%ticker%: possibly delisted; no timezone found')

Empty DataFrame
Columns: [^BVSP, Date]
Index: []

In [5]:
Carteira_IBOV_2010_2019 = ibov["^BVSP"]
Carteira_IBOV_2010_2019

Series([], Name: ^BVSP, dtype: float64)

In [6]:
len(Carteira_IBOV_2010_2019)

0

# **# CRIANDO ARQUIVO EXCEL COM PAPÉIS DA FÓRMULA MÁGICA - IBOVESPA (^BVSP)**

In [7]:
Carteira_IBOV_2010_2019_dt = ibov
Carteira_IBOV_2010_2019_dt

Empty DataFrame
Columns: [^BVSP, Date]
Index: []

In [8]:
Carteira_IBOV_2010_2019_dt['Date'] = Carteira_IBOV_2010_2019_dt.index
Carteira_IBOV_2010_2019_dt

Empty DataFrame
Columns: [^BVSP, Date]
Index: []

In [ ]:
Carteira_IBOV_2010_2019_dt['Date'] = pd.to_datetime(Carteira_IBOV_2010_2019_dt['Date']).dt.tz_localize(None)    # Convert the 'Date' column to timezone-naive datetime objects



Carteira_IBOV_2010_2019_dt.to_excel('0_7_7_DADOS_IBOV_2010_2019_dt.xlsx', index=False, engine='openpyxl')   # Criando arquivo Excel TabelaCarteiraFM.xlxl
print("Arquivo Excel criado com sucesso!")

Arquivo Excel criado com sucesso!

In [ ]:
Arq_DADOS_IBOV_2010_2019_dt = op.load_workbook('0_7_7_DADOS_IBOV_2010_2019_dt.xlsx')                                 # Carregando arquivo Excel ReesultadoFM.xlxl
Plan_DADOS_IBOV_2010_2019_dt = Arq_DADOS_IBOV_2010_2019_dt['Sheet1']                                                       # Carregando planilha Excel expec[ifica em ReesultadoFM.xlxl
Arq_DADOS_IBOV_2010_2019_dt

In [ ]:
ArqLer_DADOS_IBOV_2010_2019_dt = pd.read_excel('0_7_7_DADOS_IBOV_2010_2019_dt.xlsx')                                 # Lendo arquivo Excel ReesultadoFM.xlxl
ArqLer_DADOS_IBOV_2010_2019_dt

Empty DataFrame
Columns: [^BVSP, Date]
Index: []